// /*! JointJS+ v3.6.2 - HTML5 Diagramming Framework - TRIAL VERSION

// Copyright (c) 2022 client IO

//  2022-11-30 


// This Source Code Form is subject to the terms of the JointJS+ Trial License
// , v. 2.0. If a copy of the JointJS+ License was not distributed with this
// file, You can obtain one at http://jointjs.com/license/rappid_v2.txt
//  or from the JointJS+ archive as was distributed by client IO. See the LICENSE file.*/


// window.example = {
//     "type":"bpmn",
//     "cells":[
//        {
//           "type":"bpmn2.Activity",
//           "size":{
//              "width":205,
//              "height":80
//           },
//           "position":{
//              "x":695,
//              "y":495
//           },
//           "angle":0,
//           "id":"9af1d19f-a7cf-4b73-be00-a5d304b8f46a",
//           "z":67,
//           "embeds":[
//              "85e48685-fe19-42ce-8471-449e8c7a0db2",
//              "827dcec3-7687-49bb-ad0e-e25c0a64a2cd"
//           ],
//           "attrs":{
//              "label":{
//                 "text":""
//              }
//           }
//        },
//        {
//           "type":"bpmn2.Event",
//           "size":{
//              "width":90,
//              "height":30
//           },
//           "position":{
//              "x":710,
//              "y":515
//           },
//           "angle":0,
//           "id":"85e48685-fe19-42ce-8471-449e8c7a0db2",
//           "z":74,
//           "parent":"9af1d19f-a7cf-4b73-be00-a5d304b8f46a",
//           "attrs":{
//              "label":{
//                 "text":""
//              }
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "x":900,
//              "y":535
//           },
//           "target":{
//              "x":1020,
//              "y":595
//           },
//           "id":"4e384238-6300-4371-aaef-849725885386",
//           "z":76,
//           "vertices":[
//              {
//                 "x":1020,
//                 "y":535
//              }
//           ],
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Annotation",
//           "size":{
//              "width":45,
//              "height":30
//           },
//           "position":{
//              "x":1145,
//              "y":490
//           },
//           "angle":0,
//           "id":"42de11e7-85b7-4220-81b9-55fc773cd8cc",
//           "z":78,
//           "attrs":{
//              "body":{
//                 "fill":"#ffffff"
//              },
//              "border":{
//                 "stroke":"#fefefe"
//              },
//              "label":{
//                 "text":"Gas"
//              }
//           }
//        },
//        {
//           "type":"bpmn2.Event",
//           "size":{
//              "width":90,
//              "height":30
//           },
//           "position":{
//              "x":800,
//              "y":515
//           },
//           "angle":0,
//           "id":"827dcec3-7687-49bb-ad0e-e25c0a64a2cd",
//           "z":80,
//           "parent":"9af1d19f-a7cf-4b73-be00-a5d304b8f46a",
//           "attrs":{
//              "label":{
//                 "text":""
//              }
//           }
//        },
//        {
//           "type":"bpmn2.Annotation",
//           "size":{
//              "width":90,
//              "height":35
//           },
//           "position":{
//              "x":1125,
//              "y":610
//           },
//           "angle":0,
//           "id":"6f7c07e2-4eac-43ec-8440-4f396ab95b54",
//           "z":111,
//           "attrs":{
//              "body":{
//                 "fill":"#ffffff"
//              },
//              "border":{
//                 "stroke":"#fefefe"
//              },
//              "label":{
//                 "text":"Reflux Drum"
//              }
//           }
//        },
//        {
//           "type":"bpmn2.Event",
//           "size":{
//              "width":50,
//              "height":45
//           },
//           "position":{
//              "x":980,
//              "y":705
//           },
//           "angle":0,
//           "id":"f0ea742e-fd0d-4044-b4c5-1f403a57e955",
//           "z":112,
//           "attrs":{
//              "label":{
//                 "text":"Pump"
//              }
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "id":"f0ea742e-fd0d-4044-b4c5-1f403a57e955"
//           },
//           "target":{
//              "x":735,
//              "y":725
//           },
//           "id":"b8886d21-16bd-46bf-adb2-eeff13e891aa",
//           "z":116,
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Event",
//           "size":{
//              "width":70,
//              "height":65
//           },
//           "position":{
//              "x":815,
//              "y":880
//           },
//           "angle":0,
//           "id":"d07f3df7-3bc9-4f20-b49b-ef61893f816b",
//           "z":133,
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "id":"d07f3df7-3bc9-4f20-b49b-ef61893f816b"
//           },
//           "target":{
//              "x":920,
//              "y":910
//           },
//           "id":"b3b148b2-04fb-495c-a598-1bddb3273838",
//           "z":139,
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Annotation",
//           "size":{
//              "width":75,
//              "height":30
//           },
//           "position":{
//              "x":1170,
//              "y":705
//           },
//           "angle":0,
//           "id":"463fd8bf-4dd9-4c6c-95af-dee10cef4b5f",
//           "z":143,
//           "attrs":{
//              "body":{
//                 "fill":"#ffffff"
//              },
//              "border":{
//                 "stroke":"#fefefe"
//              },
//              "label":{
//                 "text":"Sour Water"
//              }
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "x":850,
//              "y":865
//           },
//           "target":{
//              "x":850,
//              "y":970
//           },
//           "id":"1c156246-1e0f-431c-b6ef-8c18ebe23933",
//           "z":157,
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Event",
//           "size":{
//              "width":70,
//              "height":65
//           },
//           "position":{
//              "x":815,
//              "y":1005
//           },
//           "angle":0,
//           "id":"f8ef43ec-e83e-4345-b698-546fc16b194d",
//           "z":163,
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "id":"f8ef43ec-e83e-4345-b698-546fc16b194d"
//           },
//           "target":{
//              "x":920,
//              "y":1040
//           },
//           "id":"77b8497f-06c5-41ab-b38a-0cef0c3ed63b",
//           "z":164,
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "x":850,
//              "y":990
//           },
//           "target":{
//              "x":850,
//              "y":1100
//           },
//           "id":"da94ef6b-cec5-462b-a007-18799920dccf",
//           "z":166,
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Event",
//           "size":{
//              "width":70,
//              "height":70
//           },
//           "position":{
//              "x":815,
//              "y":1140
//           },
//           "angle":0,
//           "id":"dea6f9bc-9162-4630-9025-8c20544fd4ec",
//           "z":176,
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "x":850,
//              "y":1125
//           },
//           "target":{
//              "x":850,
//              "y":1245
//           },
//           "id":"9d633ff1-e7e7-44e5-b45e-60e6aa412f84",
//           "z":177,
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "id":"dea6f9bc-9162-4630-9025-8c20544fd4ec"
//           },
//           "target":{
//              "x":925,
//              "y":1175
//           },
//           "id":"46bccad6-fd52-4e1d-a318-18e230aae2f6",
//           "z":179,
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Event",
//           "size":{
//              "width":70,
//              "height":70
//           },
//           "position":{
//              "x":815,
//              "y":1290
//           },
//           "angle":0,
//           "id":"fe523211-7cfd-46a5-bfd0-17afd80e26e7",
//           "z":184,
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "id":"fe523211-7cfd-46a5-bfd0-17afd80e26e7"
//           },
//           "target":{
//              "x":920,
//              "y":1325
//           },
//           "id":"0d0c1bb5-7eb7-4724-8bf3-aad57fe78de9",
//           "z":185,
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "x":850,
//              "y":1275
//           },
//           "target":{
//              "x":850,
//              "y":1400
//           },
//           "id":"6f25734b-e7eb-4bb1-b91c-3bbb958127aa",
//           "z":186,
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Event",
//           "size":{
//              "width":50,
//              "height":45
//           },
//           "position":{
//              "x":495,
//              "y":1360
//           },
//           "angle":0,
//           "id":"ad45a973-a8d0-4e3f-a893-94976525dae1",
//           "z":191,
//           "attrs":{
//              "label":{
//                 "text":"Pump"
//              }
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "id":"ad45a973-a8d0-4e3f-a893-94976525dae1",
//              "anchor":{
//                 "name":"topLeft",
//                 "args":{
//                    "dx":"50%",
//                    "dy":"44.444%",
//                    "rotate":true
//                 }
//              }
//           },
//           "target":{
//              "x":810,
//              "y":1325
//           },
//           "id":"87743674-454b-4224-bb4f-d929531e0306",
//           "z":192,
//           "vertices":[
//              {
//                 "x":520,
//                 "y":1320
//              }
//           ],
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "x":50,
//              "y":940
//           },
//           "target":{
//              "x":170,
//              "y":940
//           },
//           "id":"086d5dfb-3a4a-4d5a-b1ec-bd0e83012d3b",
//           "z":197,
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Activity",
//           "size":{
//              "width":195,
//              "height":70
//           },
//           "position":{
//              "x":70,
//              "y":800
//           },
//           "angle":0,
//           "id":"0d8c2b3f-02e3-4258-9271-8cb5dbbaa82d",
//           "z":200,
//           "embeds":[
             
//           ],
//           "attrs":{
//              "label":{
//                 "text":"Desalter"
//              }
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "id":"0d8c2b3f-02e3-4258-9271-8cb5dbbaa82d"
//           },
//           "target":{
//              "x":190,
//              "y":1190
//           },
//           "id":"ab88de0d-95fa-40a1-aba7-d8433add8c10",
//           "z":201,
//           "vertices":[
//              {
//                 "x":125,
//                 "y":705
//              },
//              {
//                 "x":35,
//                 "y":705
//              },
//              {
//                 "x":35,
//                 "y":885
//              },
//              {
//                 "x":100,
//                 "y":885
//              },
//              {
//                 "x":100,
//                 "y":1190
//              }
//           ],
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Gateway",
//           "size":{
//              "width":50,
//              "height":40
//           },
//           "position":{
//              "x":185,
//              "y":690
//           },
//           "angle":0,
//           "id":"aec62a7a-fc73-4bd7-8598-acfc52e53a69",
//           "z":210,
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "id":"aec62a7a-fc73-4bd7-8598-acfc52e53a69"
//           },
//           "target":{
//              "x":155,
//              "y":795
//           },
//           "id":"aa0e34ef-127b-4c0e-90ea-6d1dce8bcd62",
//           "z":211,
//           "vertices":[
//              {
//                 "x":155,
//                 "y":710
//              }
//           ],
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Gateway",
//           "size":{
//              "width":50,
//              "height":40
//           },
//           "position":{
//              "x":220,
//              "y":690
//           },
//           "angle":0,
//           "id":"ae43b68b-5945-44de-809d-15e8992a990b",
//           "z":212,
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Event",
//           "size":{
//              "width":50,
//              "height":50
//           },
//           "position":{
//              "x":175,
//              "y":550
//           },
//           "angle":0,
//           "id":"67a3a674-40f9-4156-b533-e3758544105a",
//           "z":218,
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Event",
//           "size":{
//              "width":50,
//              "height":50
//           },
//           "position":{
//              "x":245,
//              "y":550
//           },
//           "angle":0,
//           "id":"2d8c99ce-21cf-47fd-aec5-0250e057b6dd",
//           "z":219,
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Event",
//           "size":{
//              "width":50,
//              "height":50
//           },
//           "position":{
//              "x":315,
//              "y":550
//           },
//           "angle":0,
//           "id":"f3c54631-26d7-410f-a38a-15cd6e8b6545",
//           "z":220,
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "id":"f3c54631-26d7-410f-a38a-15cd6e8b6545"
//           },
//           "target":{
//              "x":270,
//              "y":710
//           },
//           "id":"b5bdbd6b-d258-4ab4-9cd9-c32699791658",
//           "z":221,
//           "vertices":[
//              {
//                 "x":425,
//                 "y":570
//              },
//              {
//                 "x":425,
//                 "y":710
//              }
//           ],
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "id":"67a3a674-40f9-4156-b533-e3758544105a"
//           },
//           "target":{
//              "x":245,
//              "y":575
//           },
//           "id":"965f90f5-49e0-4974-8789-c0f7e9c8af65",
//           "z":222,
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "x":270,
//              "y":610
//           },
//           "target":{
//              "x":270,
//              "y":530
//           },
//           "id":"3028f770-6171-41c2-8b82-35e125a1e98d",
//           "z":223,
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "x":200,
//              "y":610
//           },
//           "target":{
//              "x":200,
//              "y":530
//           },
//           "id":"dbf2fe14-0c82-48ef-9674-5fb07eb8c73e",
//           "z":224,
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "id":"2d8c99ce-21cf-47fd-aec5-0250e057b6dd"
//           },
//           "target":{
//              "x":315,
//              "y":575
//           },
//           "id":"1457ca63-7599-4498-8b20-6afda703298e",
//           "z":225,
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "x":340,
//              "y":610
//           },
//           "target":{
//              "x":340,
//              "y":530
//           },
//           "id":"47361d6a-b47c-4e83-be2b-2261bc5bcf94",
//           "z":226,
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "x":220,
//              "y":875
//           },
//           "target":{
//              "x":255,
//              "y":930
//           },
//           "id":"95b6d698-076c-4bac-99cb-f17ecb8a4904",
//           "z":231,
//           "vertices":[
//              {
//                 "x":220,
//                 "y":930
//              }
//           ],
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Event",
//           "size":{
//              "width":50,
//              "height":45
//           },
//           "position":{
//              "x":725,
//              "y":885
//           },
//           "angle":0,
//           "id":"c8dbd1de-385c-4b39-ab9a-30b1a5e25112",
//           "z":255,
//           "attrs":{
//              "label":{
//                 "text":""
//              }
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "id":"c8dbd1de-385c-4b39-ab9a-30b1a5e25112"
//           },
//           "target":{
//              "x":815,
//              "y":905
//           },
//           "id":"9149227b-f92e-4c65-a904-8cd38915b689",
//           "z":256,
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Event",
//           "size":{
//              "width":50,
//              "height":45
//           },
//           "position":{
//              "x":725,
//              "y":1145
//           },
//           "angle":0,
//           "id":"3c43c27d-7bf5-47ce-a20f-731f5b6bd397",
//           "z":258,
//           "attrs":{
//              "label":{
//                 "text":""
//              }
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "id":"3c43c27d-7bf5-47ce-a20f-731f5b6bd397"
//           },
//           "target":{
//              "x":815,
//              "y":1165
//           },
//           "id":"4f83f1eb-7542-4de5-8064-e8297a17c148",
//           "z":259,
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Event",
//           "size":{
//              "width":50,
//              "height":45
//           },
//           "position":{
//              "x":725,
//              "y":1010
//           },
//           "angle":0,
//           "id":"dbbe9010-33e7-451c-a50d-41b9b3118989",
//           "z":260,
//           "attrs":{
//              "label":{
//                 "text":""
//              }
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "id":"dbbe9010-33e7-451c-a50d-41b9b3118989"
//           },
//           "target":{
//              "x":815,
//              "y":1030
//           },
//           "id":"d7edaa4f-236e-4d5e-897e-41c49e3a2fd9",
//           "z":261,
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "x":675,
//              "y":760
//           },
//           "target":{
//              "x":725,
//              "y":905
//           },
//           "id":"cd00e002-734d-4525-a071-cf79085f2270",
//           "z":262,
//           "vertices":[
//              {
//                 "x":700,
//                 "y":760
//              },
//              {
//                 "x":700,
//                 "y":905
//              }
//           ],
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "x":675,
//              "y":915
//           },
//           "target":{
//              "x":725,
//              "y":1165
//           },
//           "id":"8771a881-9b8b-403d-819c-2694aa2bd732",
//           "z":264,
//           "vertices":[
//              {
//                 "x":700,
//                 "y":915
//              },
//              {
//                 "x":700,
//                 "y":1165
//              }
//           ],
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Annotation",
//           "size":{
//              "width":185,
//              "height":35
//           },
//           "position":{
//              "x":190,
//              "y":615
//           },
//           "angle":0,
//           "id":"09c66224-6553-4c09-a2b8-73c160ae96ac",
//           "z":276,
//           "attrs":{
//              "body":{
//                 "fill":"#ffffff"
//              },
//              "border":{
//                 "stroke":"#fefefe"
//              },
//              "label":{
//                 "text":"Hot Products are pumparound"
//              }
//           }
//        },
//        {
//           "type":"bpmn2.Annotation",
//           "size":{
//              "width":45,
//              "height":30
//           },
//           "position":{
//              "x":730,
//              "y":1195
//           },
//           "angle":0,
//           "id":"7a143a97-c61b-48a1-9b1e-6c2c223abd76",
//           "z":279,
//           "attrs":{
//              "body":{
//                 "fill":"#ffffff"
//              },
//              "border":{
//                 "stroke":"#fefefe"
//              },
//              "label":{
//                 "text":"Pump"
//              }
//           }
//        },
//        {
//           "type":"bpmn2.Annotation",
//           "size":{
//              "width":45,
//              "height":30
//           },
//           "position":{
//              "x":730,
//              "y":1060
//           },
//           "angle":0,
//           "id":"70683fc5-5238-40ab-acf6-ff758ff0a66d",
//           "z":280,
//           "attrs":{
//              "body":{
//                 "fill":"#ffffff"
//              },
//              "border":{
//                 "stroke":"#fefefe"
//              },
//              "label":{
//                 "text":"Pump"
//              }
//           }
//        },
//        {
//           "type":"bpmn2.Annotation",
//           "size":{
//              "width":45,
//              "height":30
//           },
//           "position":{
//              "x":730,
//              "y":935
//           },
//           "angle":0,
//           "id":"09ab5958-a7fc-42df-b3fd-61e07d2fc56e",
//           "z":281,
//           "attrs":{
//              "body":{
//                 "fill":"#ffffff"
//              },
//              "border":{
//                 "stroke":"#fefefe"
//              },
//              "label":{
//                 "text":"Pump"
//              }
//           }
//        },
//        {
//           "type":"bpmn2.Annotation",
//           "size":{
//              "width":65,
//              "height":30
//           },
//           "position":{
//              "x":820,
//              "y":835
//           },
//           "angle":0,
//           "id":"c424d5e0-61d4-4169-ab29-ec02b38cdabb",
//           "z":283,
//           "attrs":{
//              "body":{
//                 "fill":"#ffffff"
//              },
//              "border":{
//                 "stroke":"#fefefe"
//              },
//              "label":{
//                 "text":"crude oil"
//              }
//           }
//        },
//        {
//           "type":"bpmn2.Annotation",
//           "size":{
//              "width":65,
//              "height":30
//           },
//           "position":{
//              "x":740,
//              "y":845
//           },
//           "angle":0,
//           "id":"ce15dffc-c1d9-4bde-96ba-7155038256de",
//           "z":288,
//           "attrs":{
//              "body":{
//                 "fill":"#ffffff"
//              },
//              "border":{
//                 "stroke":"#fefefe"
//              },
//              "label":{
//                 "text":"steam"
//              }
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "id":"ce15dffc-c1d9-4bde-96ba-7155038256de"
//           },
//           "target":{
//              "x":675,
//              "y":855
//           },
//           "id":"c85a7139-1848-4c10-8d89-58712c4ceb2f",
//           "z":289,
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Annotation",
//           "size":{
//              "width":65,
//              "height":30
//           },
//           "position":{
//              "x":725,
//              "y":970
//           },
//           "angle":0,
//           "id":"0d0df51c-e4cf-408e-ac5e-3f46319ea295",
//           "z":291,
//           "attrs":{
//              "body":{
//                 "fill":"#ffffff"
//              },
//              "border":{
//                 "stroke":"#fefefe"
//              },
//              "label":{
//                 "text":"steam"
//              }
//           }
//        },
//        {
//           "type":"bpmn2.Annotation",
//           "size":{
//              "width":65,
//              "height":30
//           },
//           "position":{
//              "x":730,
//              "y":1100
//           },
//           "angle":0,
//           "id":"debea496-77a3-4e9e-a29c-4a29198d0660",
//           "z":292,
//           "attrs":{
//              "body":{
//                 "fill":"#ffffff"
//              },
//              "border":{
//                 "stroke":"#fefefe"
//              },
//              "label":{
//                 "text":"steam"
//              }
//           }
//        },
//        {
//           "type":"bpmn2.Activity",
//           "size":{
//              "width":80,
//              "height":440
//           },
//           "position":{
//              "x":595,
//              "y":720
//           },
//           "angle":0,
//           "id":"c9bd334b-e699-434f-9e90-79c029f50313",
//           "z":301,
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "id":"c9bd334b-e699-434f-9e90-79c029f50313"
//           },
//           "target":{
//              "x":725,
//              "y":1030
//           },
//           "id":"030ba1be-f62c-43ab-ab70-f993998444a1",
//           "z":302,
//           "vertices":[
//              {
//                 "x":685,
//                 "y":825
//              },
//              {
//                 "x":685,
//                 "y":1030
//              }
//           ],
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Activity",
//           "size":{
//              "width":100,
//              "height":540
//           },
//           "position":{
//              "x":435,
//              "y":660
//           },
//           "angle":0,
//           "id":"ba10fcac-28bf-41fa-9cab-1b5eb91eb9de",
//           "z":303,
//           "attrs":{
//              "label":{
//                 "text":"Crude oil distillation tower\n"
//              }
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "id":"ba10fcac-28bf-41fa-9cab-1b5eb91eb9de"
//           },
//           "target":{
//              "x":565,
//              "y":540
//           },
//           "id":"9bc079aa-8316-4c5d-96d3-f78c6c5afd75",
//           "z":304,
//           "vertices":[
//              {
//                 "x":495,
//                 "y":540
//              }
//           ],
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "id":"debea496-77a3-4e9e-a29c-4a29198d0660"
//           },
//           "target":{
//              "x":675,
//              "y":1110
//           },
//           "id":"26a27153-3fc4-485d-b085-df2c46c6926e",
//           "z":305,
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "id":"0d0df51c-e4cf-408e-ac5e-3f46319ea295"
//           },
//           "target":{
//              "x":675,
//              "y":980
//           },
//           "id":"7d4aace5-4a20-4471-816d-5bff06a7a764",
//           "z":306,
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "id":"c9bd334b-e699-434f-9e90-79c029f50313"
//           },
//           "target":{
//              "x":535,
//              "y":770
//           },
//           "id":"40ae7b2b-cf5d-4785-8aea-ea9adba1c803",
//           "z":307,
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "id":"c9bd334b-e699-434f-9e90-79c029f50313"
//           },
//           "target":{
//              "x":685,
//              "y":940
//           },
//           "id":"d9d82891-74eb-4b23-9eba-8cd2a61155dc",
//           "z":308,
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "id":"c9bd334b-e699-434f-9e90-79c029f50313"
//           },
//           "target":{
//              "x":535,
//              "y":905
//           },
//           "id":"5e76a31a-9f82-4531-8406-1bdd13af6160",
//           "z":309,
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "id":"c9bd334b-e699-434f-9e90-79c029f50313"
//           },
//           "target":{
//              "x":685,
//              "y":935
//           },
//           "id":"b789e27c-8713-4df3-a6a4-66f0afa963ee",
//           "z":310,
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "id":"c9bd334b-e699-434f-9e90-79c029f50313"
//           },
//           "target":{
//              "x":535,
//              "y":1070
//           },
//           "id":"40790d2b-fe1e-496c-b60b-164cc3fa5410",
//           "z":311,
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "id":"ba10fcac-28bf-41fa-9cab-1b5eb91eb9de"
//           },
//           "target":{
//              "x":595,
//              "y":790
//           },
//           "id":"dec0d763-0093-4d6d-8b53-80ff87467422",
//           "z":312,
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "id":"ba10fcac-28bf-41fa-9cab-1b5eb91eb9de"
//           },
//           "target":{
//              "x":595,
//              "y":925
//           },
//           "id":"a0dd03d7-fa76-437c-844d-b09333269086",
//           "z":313,
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "id":"ba10fcac-28bf-41fa-9cab-1b5eb91eb9de"
//           },
//           "target":{
//              "x":590,
//              "y":1085
//           },
//           "id":"8d871d81-13ed-4802-b31d-20bb7bfb4ef8",
//           "z":315,
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Annotation",
//           "size":{
//              "width":105,
//              "height":35
//           },
//           "position":{
//              "x":930,
//              "y":1315
//           },
//           "angle":0,
//           "id":"2b94c619-2af2-410a-8987-d488a0f7a077",
//           "z":321,
//           "attrs":{
//              "body":{
//                 "fill":"#ffffff"
//              },
//              "border":{
//                 "stroke":"#fefefe"
//              },
//              "label":{
//                 "text":"Residue(Fuel oil)"
//              }
//           }
//        },
//        {
//           "type":"bpmn2.Annotation",
//           "size":{
//              "width":100,
//              "height":35
//           },
//           "position":{
//              "x":935,
//              "y":1165
//           },
//           "angle":0,
//           "id":"f9555dc4-5c46-46fa-b265-d48f3361404c",
//           "z":322,
//           "attrs":{
//              "body":{
//                 "fill":"#ffffff"
//              },
//              "border":{
//                 "stroke":"#fefefe"
//              },
//              "label":{
//                 "text":"Heavy Gas OIl"
//              }
//           }
//        },
//        {
//           "type":"bpmn2.Annotation",
//           "size":{
//              "width":95,
//              "height":30
//           },
//           "position":{
//              "x":935,
//              "y":1030
//           },
//           "angle":0,
//           "id":"c9ac3f0e-4ebc-48ed-a1bd-a598be9f22a1",
//           "z":323,
//           "attrs":{
//              "body":{
//                 "fill":"#ffffff"
//              },
//              "border":{
//                 "stroke":"#fefefe"
//              },
//              "label":{
//                 "text":"Light Gas Oil"
//              }
//           }
//        },
//        {
//           "type":"bpmn2.Annotation",
//           "size":{
//              "width":100,
//              "height":35
//           },
//           "position":{
//              "x":935,
//              "y":900
//           },
//           "angle":0,
//           "id":"bd7fac18-7824-49b4-89a4-f00f4d09ec8c",
//           "z":324,
//           "attrs":{
//              "body":{
//                 "fill":"#ffffff"
//              },
//              "border":{
//                 "stroke":"#fefefe"
//              },
//              "label":{
//                 "text":"Kero (Jet Fuel)"
//              }
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "x":55,
//              "y":1115
//           },
//           "target":{
//              "x":165,
//              "y":1115
//           },
//           "id":"a150579b-60f1-484f-afe8-2e0ea86d63b1",
//           "z":330,
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Event",
//           "size":{
//              "width":60,
//              "height":55
//           },
//           "position":{
//              "x":70,
//              "y":1090
//           },
//           "angle":0,
//           "id":"12ff1f9d-29f9-4dad-ae28-99bc6f52f78b",
//           "z":331,
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "x":50,
//              "y":1030
//           },
//           "target":{
//              "x":175,
//              "y":1030
//           },
//           "id":"ce734af8-6558-4fd6-8bbe-743ec39e1da9",
//           "z":332,
//           "vertices":[
             
//           ],
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Event",
//           "size":{
//              "width":60,
//              "height":55
//           },
//           "position":{
//              "x":70,
//              "y":1000
//           },
//           "angle":0,
//           "id":"8e1ed52c-d07d-40c6-be68-3564bd0d2ba0",
//           "z":333,
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Event",
//           "size":{
//              "width":60,
//              "height":55
//           },
//           "position":{
//              "x":70,
//              "y":915
//           },
//           "angle":0,
//           "id":"81af6a3c-940c-4f7f-b71c-dad513d88c20",
//           "z":334,
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Annotation",
//           "size":{
//              "width":70,
//              "height":35
//           },
//           "position":{
//              "x":110,
//              "y":1195
//           },
//           "angle":0,
//           "id":"edd2b0ff-68f1-4ada-a804-11aeb3c2c297",
//           "z":335,
//           "attrs":{
//              "body":{
//                 "fill":"#ffffff"
//              },
//              "border":{
//                 "stroke":"#fefefe"
//              },
//              "label":{
//                 "text":"Crude Oil"
//              }
//           }
//        },
//        {
//           "type":"bpmn2.Activity",
//           "size":{
//              "width":120,
//              "height":100
//           },
//           "position":{
//              "x":195,
//              "y":1110
//           },
//           "angle":0,
//           "id":"2adde23c-49f5-4f31-82f2-52b4e7e3fbef",
//           "z":336,
//           "attrs":{
//              "label":{
//                 "text":"Fired Heater"
//              }
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "id":"2adde23c-49f5-4f31-82f2-52b4e7e3fbef"
//           },
//           "target":{
//              "x":425,
//              "y":1125
//           },
//           "id":"0aef84ee-2fdc-48b3-b8dc-10ad31c7e6d0",
//           "z":337,
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Annotation",
//           "size":{
//              "width":65,
//              "height":35
//           },
//           "position":{
//              "x":460,
//              "y":670
//           },
//           "angle":0,
//           "id":"7db5311b-76f5-45de-86fd-73c9b91753e3",
//           "z":338,
//           "attrs":{
//              "body":{
//                 "fill":"#ffffff"
//              },
//              "border":{
//                 "stroke":"#fefefe"
//              },
//              "label":{
//                 "text":"2 atm"
//              }
//           }
//        },
//        {
//           "type":"bpmn2.Annotation",
//           "size":{
//              "width":75,
//              "height":30
//           },
//           "position":{
//              "x":1100,
//              "y":790
//           },
//           "angle":0,
//           "id":"afb97511-5fba-46e3-bcf7-cc2f77e5fa3e",
//           "z":339,
//           "attrs":{
//              "body":{
//                 "fill":"#ffffff"
//              },
//              "border":{
//                 "stroke":"#fefefe"
//              },
//              "label":{
//                 "text":"Naphtha"
//              }
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "id":"afb97511-5fba-46e3-bcf7-cc2f77e5fa3e"
//           },
//           "target":{
//              "x":540,
//              "y":680
//           },
//           "id":"8feacbdb-2f5a-4bc1-ab1f-4344c35229dd",
//           "z":340,
//           "vertices":[
//              {
//                 "x":735,
//                 "y":805
//              },
//              {
//                 "x":735,
//                 "y":680
//              }
//           ],
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "id":"ba10fcac-28bf-41fa-9cab-1b5eb91eb9de"
//           },
//           "target":{
//              "x":735,
//              "y":750
//           },
//           "id":"886d3275-6039-4c41-be77-9dcf2919b0c3",
//           "z":341,
//           "vertices":[
//              {
//                 "x":735,
//                 "y":680
//              }
//           ],
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Annotation",
//           "size":{
//              "width":75,
//              "height":30
//           },
//           "position":{
//              "x":590,
//              "y":645
//           },
//           "angle":0,
//           "id":"377f029e-daa6-4360-a5d7-c1b2c65f5065",
//           "z":342,
//           "attrs":{
//              "body":{
//                 "fill":"#ffffff"
//              },
//              "border":{
//                 "stroke":"#fefefe"
//              },
//              "label":{
//                 "text":"Reflux"
//              }
//           }
//        },
//        {
//           "type":"bpmn2.Annotation",
//           "size":{
//              "width":95,
//              "height":55
//           },
//           "position":{
//              "x":195,
//              "y":980
//           },
//           "angle":0,
//           "id":"ea0024f4-a2a3-417a-919d-b5b772a16b8f",
//           "z":343,
//           "attrs":{
//              "body":{
//                 "fill":"#ffffff"
//              },
//              "border":{
//                 "stroke":"#fefefe"
//              },
//              "label":{
//                 "text":"Hot Products are pumparound"
//              }
//           }
//        },
//        {
//           "type":"bpmn2.Annotation",
//           "size":{
//              "width":65,
//              "height":30
//           },
//           "position":{
//              "x":345,
//              "y":1160
//           },
//           "angle":0,
//           "id":"424d6647-8ee7-4ef8-b6fd-e122c4f29b11",
//           "z":344,
//           "attrs":{
//              "body":{
//                 "fill":"#ffffff"
//              },
//              "border":{
//                 "stroke":"#fefefe"
//              },
//              "label":{
//                 "text":"steam"
//              }
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "id":"424d6647-8ee7-4ef8-b6fd-e122c4f29b11"
//           },
//           "target":{
//              "x":435,
//              "y":1170
//           },
//           "id":"b2ff5db5-f66b-4cc7-9903-8bee84ae506b",
//           "z":345,
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Annotation",
//           "size":{
//              "width":65,
//              "height":30
//           },
//           "position":{
//              "x":335,
//              "y":1090
//           },
//           "angle":0,
//           "id":"464a7581-ea3e-47df-822b-b904d5f087f7",
//           "z":346,
//           "attrs":{
//              "body":{
//                 "fill":"#ffffff"
//              },
//              "border":{
//                 "stroke":"#fefefe"
//              },
//              "label":{
//                 "text":"398C"
//              }
//           }
//        },
//        {
//           "type":"bpmn2.Annotation",
//           "size":{
//              "width":55,
//              "height":35
//           },
//           "position":{
//              "x":260,
//              "y":920
//           },
//           "angle":0,
//           "id":"983b153b-93ea-4dd5-b937-c4d0afcf40b4",
//           "z":347,
//           "attrs":{
//              "body":{
//                 "fill":"#ffffff"
//              },
//              "border":{
//                 "stroke":"#fefefe"
//              },
//              "label":{
//                 "text":"Brine"
//              }
//           }
//        },
//        {
//           "type":"bpmn2.Annotation",
//           "size":{
//              "width":80,
//              "height":30
//           },
//           "position":{
//              "x":190,
//              "y":735
//           },
//           "angle":0,
//           "id":"67fa527f-7dcf-4c17-aa57-141650b10f62",
//           "z":348,
//           "attrs":{
//              "body":{
//                 "fill":"#ffffff"
//              },
//              "border":{
//                 "stroke":"#fefefe"
//              },
//              "label":{
//                 "text":"Mixing water"
//              }
//           }
//        },
//        {
//           "type":"bpmn2.Annotation",
//           "size":{
//              "width":45,
//              "height":30
//           },
//           "position":{
//              "x":320,
//              "y":735
//           },
//           "angle":0,
//           "id":"bdd7cd3b-c56a-4d90-b16b-312bdb773536",
//           "z":351,
//           "attrs":{
//              "body":{
//                 "fill":"#ffffff"
//              },
//              "border":{
//                 "stroke":"#fefefe"
//              },
//              "label":{
//                 "text":"water"
//              }
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "id":"bdd7cd3b-c56a-4d90-b16b-312bdb773536"
//           },
//           "target":{
//              "x":345,
//              "y":710
//           },
//           "id":"7dec3861-f06d-4838-9cd8-95f6181d3812",
//           "z":352,
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "id":"f3c54631-26d7-410f-a38a-15cd6e8b6545"
//           },
//           "target":{
//              "x":425,
//              "y":615
//           },
//           "id":"e4ac42a5-e4a9-445e-9aac-4055a3ef5b2b",
//           "z":353,
//           "vertices":[
//              {
//                 "x":425,
//                 "y":570
//              }
//           ],
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "x":300,
//              "y":820
//           },
//           "target":{
//              "x":425,
//              "y":820
//           },
//           "id":"e0af9ba9-476c-4d81-a289-3fbf6b67af89",
//           "z":355,
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Event",
//           "size":{
//              "width":50,
//              "height":50
//           },
//           "position":{
//              "x":355,
//              "y":875
//           },
//           "angle":0,
//           "id":"446142a4-11dd-4342-8871-27c78f7f69db",
//           "z":360,
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Event",
//           "size":{
//              "width":70,
//              "height":65
//           },
//           "position":{
//              "x":315,
//              "y":790
//           },
//           "angle":0,
//           "id":"2ddddbe2-8bad-452f-b840-df51c2075049",
//           "z":365,
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "id":"446142a4-11dd-4342-8871-27c78f7f69db"
//           },
//           "target":{
//              "id":"2ddddbe2-8bad-452f-b840-df51c2075049"
//           },
//           "id":"1db3f2cd-d505-48fe-8af9-3e8ea5406245",
//           "z":366,
//           "vertices":[
//              {
//                 "x":335,
//                 "y":900
//              }
//           ],
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "id":"2ddddbe2-8bad-452f-b840-df51c2075049"
//           },
//           "target":{
//              "id":"ba10fcac-28bf-41fa-9cab-1b5eb91eb9de"
//           },
//           "id":"fc07bc27-fe55-4cd9-a2d9-560b2d95a947",
//           "z":366,
//           "vertices":[
//              {
//                 "x":350,
//                 "y":755
//              }
//           ],
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "x":425,
//              "y":865
//           },
//           "target":{
//              "x":365,
//              "y":895
//           },
//           "id":"f9157599-8342-468f-a505-17f26c834687",
//           "z":367,
//           "vertices":[
//              {
//                 "x":425,
//                 "y":895
//              }
//           ],
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Annotation",
//           "size":{
//              "width":85,
//              "height":35
//           },
//           "position":{
//              "x":340,
//              "y":930
//           },
//           "angle":0,
//           "id":"62ee70ce-30fd-4dc0-b14a-7b8f41edb67f",
//           "z":368,
//           "attrs":{
//              "body":{
//                 "fill":"#ffffff"
//              },
//              "border":{
//                 "stroke":"#fefefe"
//              },
//              "label":{
//                 "text":"pump around"
//              }
//           }
//        },
//        {
//           "type":"bpmn2.Annotation",
//           "size":{
//              "width":105,
//              "height":35
//           },
//           "position":{
//              "x":445,
//              "y":1235
//           },
//           "angle":0,
//           "id":"6f156d7f-74a1-4f0e-bb97-41913069b61d",
//           "z":373,
//           "attrs":{
//              "body":{
//                 "fill":"#ffffff"
//              },
//              "border":{
//                 "stroke":"#fefefe"
//              },
//              "label":{
//                 "text":"sidecut strippers"
//              }
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "id":"6f156d7f-74a1-4f0e-bb97-41913069b61d"
//           },
//           "target":{
//              "x":605,
//              "y":1165
//           },
//           "id":"a26ff47c-5463-4b93-a242-7249a0e4979d",
//           "z":374,
//           "vertices":[
//              {
//                 "x":555,
//                 "y":1215
//              }
//           ],
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Annotation",
//           "size":{
//              "width":60,
//              "height":30
//           },
//           "position":{
//              "x":320,
//              "y":805
//           },
//           "angle":0,
//           "id":"5278ddeb-8a52-440f-991c-ef3889feeb50",
//           "z":375,
//           "attrs":{
//              "body":{
//                 "fill":"#ffffff"
//              },
//              "border":{
//                 "stroke":"#fefefe"
//              },
//              "label":{
//                 "text":"crude oil"
//              }
//           }
//        },
//        {
//           "type":"bpmn2.Annotation",
//           "size":{
//              "width":45,
//              "height":30
//           },
//           "position":{
//              "x":115,
//              "y":470
//           },
//           "angle":0,
//           "id":"c9d2f0d4-7778-47e5-8b1a-de330cd07f59",
//           "z":376,
//           "attrs":{
//              "body":{
//                 "fill":"#ffffff"
//              },
//              "border":{
//                 "stroke":"#fefefe"
//              },
//              "label":{
//                 "text":"Pump"
//              }
//           }
//        },
//        {
//           "type":"bpmn2.Annotation",
//           "size":{
//              "width":125,
//              "height":30
//           },
//           "position":{
//              "x":720,
//              "y":455
//           },
//           "angle":0,
//           "id":"04c9fff1-ddcb-4894-b8cf-f92b6b7d705b",
//           "z":377,
//           "attrs":{
//              "body":{
//                 "fill":"#ffffff"
//              },
//              "border":{
//                 "stroke":"#fefefe"
//              },
//              "label":{
//                 "text":"Air cooled condenser"
//              }
//           }
//        },
//        {
//           "type":"bpmn2.Event",
//           "size":{
//              "width":50,
//              "height":45
//           },
//           "position":{
//              "x":160,
//              "y":425
//           },
//           "angle":0,
//           "id":"a789163c-4f14-47d2-b07d-2a3ba0414614",
//           "z":383,
//           "attrs":{
//              "label":{
//                 "text":""
//              }
//           }
//        },
//        {
//           "type":"bpmn2.Gateway",
//           "size":{
//              "width":58,
//              "height":58
//           },
//           "position":{
//              "x":70,
//              "y":485
//           },
//           "angle":0,
//           "id":"7cacc48a-8c98-4540-85ef-3cfaf09fe364",
//           "z":387,
//           "attrs":{
//              "body":{
//                 "stroke":"#0f1010"
//              },
//              "label":{
//                 "text":"Crude Oil\n"
//              }
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "id":"7cacc48a-8c98-4540-85ef-3cfaf09fe364"
//           },
//           "target":{
//              "x":155,
//              "y":450
//           },
//           "id":"0ff344b2-8931-4b89-a00f-472712bd3baa",
//           "z":388,
//           "vertices":[
//              {
//                 "x":100,
//                 "y":450
//              }
//           ],
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Event",
//           "size":{
//              "width":50,
//              "height":50
//           },
//           "position":{
//              "x":565,
//              "y":515
//           },
//           "angle":0,
//           "id":"eeefd299-3dea-4c9b-8f90-ed47e94c89c0",
//           "z":391,
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "id":"a789163c-4f14-47d2-b07d-2a3ba0414614"
//           },
//           "target":{
//              "id":"eeefd299-3dea-4c9b-8f90-ed47e94c89c0"
//           },
//           "id":"237627a0-65d1-46ee-b592-10cc0e7588e0",
//           "z":392,
//           "vertices":[
//              {
//                 "x":600,
//                 "y":450
//              }
//           ],
//           "labels":[
//              {
//                 "attrs":{
//                    "label":{
//                       "text":"1"
//                    }
//                 }
//              }
//           ],
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "id":"eeefd299-3dea-4c9b-8f90-ed47e94c89c0"
//           },
//           "target":{
//              "x":170,
//              "y":575
//           },
//           "id":"68d2b468-3df1-48ba-92ef-e468b71776a6",
//           "z":392,
//           "vertices":[
//              {
//                 "x":575,
//                 "y":505
//              },
//              {
//                 "x":150,
//                 "y":505
//              },
//              {
//                 "x":150,
//                 "y":575
//              }
//           ],
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "id":"eeefd299-3dea-4c9b-8f90-ed47e94c89c0"
//           },
//           "target":{
//              "id":"9af1d19f-a7cf-4b73-be00-a5d304b8f46a"
//           },
//           "id":"55dec077-eb06-4bc1-ac2d-6d8ef80efe83",
//           "z":392,
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Activity",
//           "size":{
//              "width":180,
//              "height":70
//           },
//           "position":{
//              "x":935,
//              "y":600
//           },
//           "angle":0,
//           "id":"15d7b317-b83c-46b7-a552-9ffae67a9282",
//           "z":395,
//           "attrs":{
//              "label":{
//                 "text":"43 C"
//              }
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "id":"15d7b317-b83c-46b7-a552-9ffae67a9282"
//           },
//           "target":{
//              "id":"f0ea742e-fd0d-4044-b4c5-1f403a57e955"
//           },
//           "id":"0366ccd1-48cf-4226-bcac-8ef704a06f24",
//           "z":396,
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "id":"15d7b317-b83c-46b7-a552-9ffae67a9282",
//              "anchor":{
//                 "name":"topLeft",
//                 "args":{
//                    "dx":"75%",
//                    "dy":"50%",
//                    "rotate":true
//                 }
//              }
//           },
//           "target":{
//              "x":1155,
//              "y":715
//           },
//           "id":"7fe05bfd-7db2-417e-9a23-449048000b29",
//           "z":396,
//           "vertices":[
//              {
//                 "x":1070,
//                 "y":715
//              }
//           ],
//           "attrs":{
             
//           }
//        },
//        {
//           "type":"bpmn2.Flow",
//           "source":{
//              "id":"15d7b317-b83c-46b7-a552-9ffae67a9282"
//           },
//           "target":{
//              "x":1145,
//              "y":505
//           },
//           "id":"32a8a98b-b360-48af-8431-ae5f9ced5428",
//           "z":396,
//           "vertices":[
//              {
//                 "x":1090,
//                 "y":505
//              }
//           ],
//           "labels":[
//              {
//                 "attrs":{
//                    "label":{
//                       "text":""
//                    }
//                 }
//              }
//           ],
//           "attrs":{
             
//           }
//        }
//     ]
//  }